
api:

alexa:
  smarter_home:

media_player:
  - platform:  broadlink
    host: 192.168.1.11
    mac: '77:FF:77:55:CC:66'
    name: tv 
    ping_host: 192.168.1.12
    channels:
        city: 7
        pulse: 24
        amc: 31
    codes:
        turn_on: JgBQAAABKZEVERQRFBEUERUQFRAVNRUQFTYUNhU1FTUVNRU2FBEVNRUQFTUVEBURFDYVEBUQFRAVNRUQFTYUNhUQFTUVNRU2FAAFFQABKEkTAA0FAAAAAAAAAAA= | JgBkAG5vG1QbVBscG1QbVBtUG1QcUxwbHBwbHBscGxwcUxwcGxwbHBscHBwbVBtUG1QbAATXbm8bVBtUGxwbVBtUG1QbVBtUGxwcGxwcGxwbHBxTHBscHBscGxwcGxxTHFMcUxwADQUAAAAA
        turn_off: JgBQAAABKZEVERQRFBEUERUQFRAVNRUQFTYUNhU1FTUVNRU2FBEVNRUQFTUVEBURFDYVEBUQFRAVNRUQFTYUNhUQFTUVNRU2FAAFFQABKEkTAA0FAAAAAAAAAAA= | JgBkAG5vG1QbVBscG1QbVBtUG1QcUxwbHBwbHBscGxwcUxwcGxwbHBscHBwbVBtUG1QbAATXbm8bVBtUGxwbVBtUG1QbVBtUGxwcGxwcGxwbHBxTHBscHBscGxwcGxxTHFMcUxwADQUAAAAA
        volume_up: JgBYAAABJ5QTEhMSExITEhMSExMSOBITEzcTNxM4EjgSOBM3ExITOBITEjgTEhM3EzcTExITEhMSOBMSEzcTEhMTEjgSOBM3EwAFFQABJ0oSAAxWAAEmShMADQU=
        volume_down: JgBYAAABJ5QSExITExITEhMSExITOBITEjgTNxM3EzgSOBI4ExITNxMSEzgSOBM3EzcTEhMTEhMSOBITExITEhMSEzcTOBI4EwAFFgABJ0oTAAxWAAEnShIADQU=
        next_channel: JgBkAG9uHFMcUxwcG1QbVBtUGxwbVBtUG1QbHBwcGxwbVBscGxwcGxxUGxwbHBscHFMcAATWbm8cUxxTHBscVBtUG1QbHBtUG1QbVBscHBscHBtUGxwbHBwbHFMcHBscGxwcUxwADQUAAAAA
        previous_channel: JgAyAG5vG1QbVBscHFMcUxwbHFQbVBtUG1QbHBscHBscUxwcGxwbVBscHBscHBscG1QbAA0FAAAAAAAA
        mute: JgBYAAABJ5QTEhMSExITEhMTEhMSOBMSEzcTNxM4EjgTNxM3ExITOBITEhMSExMSEzcTEhMSExMSOBI4EzcTNxMTEjgSOBM3EwAFFwABJ0kTAAxUAAEnShMADQU=
        enter: gBkAG5vG1QcUxwbHFMcUxwcGxwbVBtUGxwcGxwcGxwbVBscHBscUxxTHBwbHBtUG1QbAATWbm4cVBtUGxwbVBtUGxwcGxxTHFMcHBscGxwcGxxTHBwbHBtUG1QbHBwbHFMcVBsADQUAAAAA
         play: JgCWAG5vG1QbVBscG1QcUxxTHFMcGxwcG1QbVBscGxwcUxwcGxwbHBscHFMcUxwcGxwbAATVb24cUxxTHRsbVBtUHFMbVBscGxwcUxxTHBwbHBtUGxwbHBwcGxwbVBtUGxwbHBwABNVubxtUHFMcGxxTHFMcUxxUGxwbHBtUG1QbHBwcG1QbHBscGxwcGxxUG1QbHBscGwANBQAA
        pause: JgBkAG5vG1QbVBscHFMcUxxTHBscUxwcGxwbHBwbHBwbVBscGxwcGxxTHBwbVBtUG1QbAATXbm8bVBtUGxwbVBtUG1QcGxxTHBwbHBscGxwcHBtUGxwbHBscHFMcHBtUG1QbVBsADQUAAAAA
        stop: JgCWAG5vG1QbVBscHFMcUxwbHBwbVBscG1QbVBscHBscVBscGxwbVBtUGxwcUxwcGxwbAATVb24cUxxTHBwbVBtUGxwbHBxTHBscUxxUGxwbHBtUGxwcGxxTHFQbHBtUGxwbHBwABNZubxtUHVIbHBtUG1QbHBwbHFMcHBtUG1QbHBscHFMcGxwcG1QbVBscG1QcGxwcGwANBQAA
        key_0: JgBkAG9uHFMcUxwcG1QbVBtUGxwbHBxTHFMcGxwcGxwbVBscHBscHBtUG1QbHBscHFMcAATXbm8bVBtUGxwbVBtUG1QbHBwbHFQbVBscGxwbHBxTHBwbHBscG1QbVBscHBwbVBsADQUAAAAA
        key_1: JgBkAG9uHFMcUxwcG1QbVBscGxwbHBwcG1QbHBscGxwcUxwcGxwbVBtUG1QbVBscHFMcAATWbm8cUxxTHBscUxxTHBwbHBscHBscUxwcGxwbHBxTHBscHBtUG1QbVBtUGxwbVBwADQUAAAAA
        key_2: JgBkAG9uHFMcUxwcG1QbVBtUGxwbHBwbHFQbHBscGxwcUxwbHBwbHBtUG1QbVBscHFMcAATWbm8cUxxTHBscVBtUG1QbHBscGxwcUxwcGxwbHBtUGxwcHBscG1QbVBtUGxwcUxwADQUAAAAA
        key_3: JgBkAG5vG1QbVBscHFMcUxwcG1QbHBscHFMcGxwcGxwbVBscHBscUxwcG1QbVBscG1QbAATWbm4cVBtUGxwbVBtUGxwcUxwbHBwbVBscGxwcGxxTHBwbHBtUGxwcUxxTHBscUxwADQUAAAAA
        key_4: JgBkAG5vG1QbVBscHFMcUxxTHFMcHBscG1QbHBwbHBwbVBscGxwbHBwbHFMcVBscG1QbAATXbm8bVBtUGxwbVBtUHFMcUxwbHBwbVBscGxwcGxxTHBwbHBscHBscUxxTHBwbVBsADQUAAAAA
        key_5: JgBkAG5vG1QbVBscHFMcUxwcGxwbVBscG1QbHBwcGxwbVBscGxwcUxxTHBwbVBscG1QbAATVb24cUxxTHBwbVBtUGxwbHBxTHBwbVBscGxwbHBxTHBwbHBtUG1QbHBxTHBscUxwADQUAAAAA
        key_6: JgBkAG5vG1QbVBscHFMcUxxTHBwbVBwbG1QbHBscHBwbVBscGxwbHBxTHBwbVBscG1QbAATVb24cUxxTHBwbVBtUG1QbHBtUGxwcUxwbHBwbHBxTGxwcGxwcG1QbHBtUGxwcUxwADQUAAAAA
        key_7: JgBkAG5vHFMcUxwbHFMcVBscG1QbVBscHFMcGxwcGxwbVBscGxwcUxwcGxwbVBscG1QcAATUbm8bVBtUGxwcUxxTHBwbVBtUGxwbVBscHBscHBtUGxwbHBxTHBscHBtUGxwbVBsADQUAAAAA
        key_8: JgBkAG5vG1QbVBscHFMcUxxTHFMcUxwcG1QbHBscHBscUxwcGxwbHBwbHBwbVBscG1QbAATVbm8bVBtUGxwcUxxTHFMcUxxTHBwbVBscGxwbHBxTHBwbHBscGxwcGxxTHBwbVBsADQUAAAAA
        key_9: JgBkAG5vG1QbVBscG1QcUxwbHBwbHBtUG1QbHBwbHBwbVBscGxwcUxxTHFMcHBscG1QbAATXb24cUxxTHBwbVBtUGxwbHBwbHFMcUxwcGxwbHBxTHBscHBtUG1QbVBscGxwcUxwADQUAAAAA
    sources:
      - name: "Cable" 
        code: JgBWAAABJpITERMSExITEhMRExITNxMSEzcTNxM3EzcTNxM3ExITNxM3ExITEhMRExITNxMSExETEhM3EzcTNxM3ExITNxM3EwAFNgABJkkTAAxiAAEmSROSDQU=

      - name: "Chromecast"
        code: JgBWAAABJpITERMSExITEhMRExITNxMSEzcTNxM3EzcTNxM3ExITNxMSExITNxMRExITNxMSExETNxM3ExITNxM3ExITNxM3EwAFNgABJkkTAAxiAAEmSROSDQU=


input_text:
    tv_channel:
        name: TV Channel
        min: 0 
        max: 5 
        pattern: '[a-z|A-Z|0-9]*'
        initial: '' 
 

